apiVersion: v1
kind: Namespace
metadata:
  name: nginx-server-prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/berkayh27/nov-argocd.git
    targetRevision: 1.6.0
    path: ./
    helm:
      values: |
        global:
          env: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-server-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true